# Generated by Django 4.2.4 on 2023-08-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_user_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.TextField(blank=True, null=True),
        ),
    ]
