# Generated by Django 4.2.4 on 2023-08-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryoptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='deliveryoptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deliveryoptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='expirydate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='susratings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='backend\\media'),
        ),
    ]
