# Generated by Django 4.2.4 on 2023-08-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_deliveryoptions_orderitem_deliveryoptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deliveryoptions',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='expirydate',
            field=models.DateField(null=True),
        ),
    ]
